<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Car;
use App\Models\Category;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category IDs for reference
        $sportsCars = Category::where('name', 'Sports Cars')->first();
        $suvs = Category::where('name', 'SUVs')->first();
        $sedans = Category::where('name', 'Sedans')->first();
        $luxury = Category::where('name', 'Luxury Vehicles')->first();
        $electric = Category::where('name', 'Electric Vehicles')->first();

        // Sports Cars
        Car::create([
            'category_id' => $sportsCars->id,
            'ref_no' => 'CAR-SPORTS-001',
            'make' => 'Ferrari',
            'model' => '488',
            'model_code' => 'F488',
            'variant' => 'GTB',
            'year' => 2020,
            'reg_year_month' => '2020-03',
            'mileage_km' => 15000,
            'engine_cc' => 3902,
            'transmission' => 'Automatic',
            'drive' => 'RWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Red',
            'seats' => 2,
            'grade_overall' => 4.5,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 250000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'ZFF******G******',
            'location' => 'Tokyo, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Excellent condition, low mileage sports car',
        ]);

        Car::create([
            'category_id' => $sportsCars->id,
            'ref_no' => 'CAR-SPORTS-002',
            'make' => 'Porsche',
            'model' => '911',
            'model_code' => 'P911',
            'variant' => 'Carrera S',
            'year' => 2021,
            'reg_year_month' => '2021-06',
            'mileage_km' => 8000,
            'engine_cc' => 2981,
            'transmission' => 'Automatic',
            'drive' => 'RWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'White',
            'seats' => 2,
            'grade_overall' => 4.8,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 180000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'WP0******K******',
            'location' => 'Osaka, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Mint condition Porsche 911',
        ]);

        // SUVs
        Car::create([
            'category_id' => $suvs->id,
            'ref_no' => 'CAR-SUV-001',
            'make' => 'Toyota',
            'model' => 'Land Cruiser',
            'model_code' => 'TLC200',
            'variant' => 'VX',
            'year' => 2019,
            'reg_year_month' => '2019-09',
            'mileage_km' => 45000,
            'engine_cc' => 4608,
            'transmission' => 'Automatic',
            'drive' => '4WD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Silver',
            'seats' => 7,
            'grade_overall' => 4.2,
            'grade_exterior' => 'B',
            'grade_interior' => 'A',
            'price_amount' => 85000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'JTE******K******',
            'location' => 'Yokohama, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Reliable family SUV',
        ]);

        Car::create([
            'category_id' => $suvs->id,
            'ref_no' => 'CAR-SUV-002',
            'make' => 'Lexus',
            'model' => 'RX',
            'model_code' => 'LRX350',
            'variant' => 'F Sport',
            'year' => 2020,
            'reg_year_month' => '2020-12',
            'mileage_km' => 25000,
            'engine_cc' => 3456,
            'transmission' => 'Automatic',
            'drive' => 'AWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Black',
            'seats' => 5,
            'grade_overall' => 4.6,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 65000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => '2T2******K******',
            'location' => 'Nagoya, Japan',
            'country_origin' => 'Japan',
            'status' => 'reserved',
            'notes' => 'Luxury SUV with premium features',
        ]);

        // Sedans
        Car::create([
            'category_id' => $sedans->id,
            'ref_no' => 'CAR-SEDAN-001',
            'make' => 'Honda',
            'model' => 'Accord',
            'model_code' => 'HACC',
            'variant' => 'EX-L',
            'year' => 2021,
            'reg_year_month' => '2021-04',
            'mileage_km' => 18000,
            'engine_cc' => 1993,
            'transmission' => 'Automatic',
            'drive' => 'FWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Blue',
            'seats' => 5,
            'grade_overall' => 4.3,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 28000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => '1HGC******K******',
            'location' => 'Kobe, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Reliable family sedan',
        ]);

        Car::create([
            'category_id' => $sedans->id,
            'ref_no' => 'CAR-SEDAN-002',
            'make' => 'Toyota',
            'model' => 'Camry',
            'model_code' => 'TCAM',
            'variant' => 'XSE',
            'year' => 2020,
            'reg_year_month' => '2020-08',
            'mileage_km' => 32000,
            'engine_cc' => 2487,
            'transmission' => 'Automatic',
            'drive' => 'FWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'White',
            'seats' => 5,
            'grade_overall' => 4.1,
            'grade_exterior' => 'B',
            'grade_interior' => 'A',
            'price_amount' => 25000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => '4T1******K******',
            'location' => 'Fukuoka, Japan',
            'country_origin' => 'Japan',
            'status' => 'sold',
            'notes' => 'Popular family sedan',
        ]);

        // Luxury Vehicles
        Car::create([
            'category_id' => $luxury->id,
            'ref_no' => 'CAR-LUXURY-001',
            'make' => 'Mercedes-Benz',
            'model' => 'S-Class',
            'model_code' => 'MBS350',
            'variant' => 'Long Wheelbase',
            'year' => 2021,
            'reg_year_month' => '2021-01',
            'mileage_km' => 12000,
            'engine_cc' => 2925,
            'transmission' => 'Automatic',
            'drive' => 'RWD',
            'steering' => 'Right',
            'fuel' => 'Diesel',
            'color' => 'Black',
            'seats' => 5,
            'grade_overall' => 4.9,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 120000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'WDD******K******',
            'location' => 'Tokyo, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Ultimate luxury sedan',
        ]);

        Car::create([
            'category_id' => $luxury->id,
            'ref_no' => 'CAR-LUXURY-002',
            'make' => 'BMW',
            'model' => '7 Series',
            'model_code' => 'BMW750',
            'variant' => 'xDrive',
            'year' => 2020,
            'reg_year_month' => '2020-11',
            'mileage_km' => 22000,
            'engine_cc' => 4395,
            'transmission' => 'Automatic',
            'drive' => 'AWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Silver',
            'seats' => 5,
            'grade_overall' => 4.7,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 95000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'WBA******K******',
            'location' => 'Osaka, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Executive luxury sedan',
        ]);

        // Electric Vehicles
        Car::create([
            'category_id' => $electric->id,
            'ref_no' => 'CAR-EV-001',
            'make' => 'Tesla',
            'model' => 'Model 3',
            'model_code' => 'TSL3',
            'variant' => 'Long Range',
            'year' => 2021,
            'reg_year_month' => '2021-05',
            'mileage_km' => 15000,
            'engine_cc' => null,
            'transmission' => 'Automatic',
            'drive' => 'AWD',
            'steering' => 'Right',
            'fuel' => 'Electric',
            'color' => 'White',
            'seats' => 5,
            'grade_overall' => 4.6,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 55000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => '5YJ******K******',
            'location' => 'Yokohama, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Popular electric sedan',
        ]);

        Car::create([
            'category_id' => $electric->id,
            'ref_no' => 'CAR-EV-002',
            'make' => 'Nissan',
            'model' => 'Leaf',
            'model_code' => 'NLEAF',
            'variant' => 'e+',
            'year' => 2020,
            'reg_year_month' => '2020-07',
            'mileage_km' => 28000,
            'engine_cc' => null,
            'transmission' => 'Automatic',
            'drive' => 'FWD',
            'steering' => 'Right',
            'fuel' => 'Electric',
            'color' => 'Blue',
            'seats' => 5,
            'grade_overall' => 4.2,
            'grade_exterior' => 'B',
            'grade_interior' => 'A',
            'price_amount' => 35000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => '1N4******K******',
            'location' => 'Kobe, Japan',
            'country_origin' => 'Japan',
            'status' => 'reserved',
            'notes' => 'Reliable electric vehicle',
        ]);

        // More cars for variety
        Car::create([
            'category_id' => $sportsCars->id,
            'ref_no' => 'CAR-SPORTS-003',
            'make' => 'Lamborghini',
            'model' => 'Huracan',
            'model_code' => 'LHU',
            'variant' => 'EVO',
            'year' => 2022,
            'reg_year_month' => '2022-02',
            'mileage_km' => 5000,
            'engine_cc' => 5204,
            'transmission' => 'Automatic',
            'drive' => 'AWD',
            'steering' => 'Right',
            'fuel' => 'Petrol',
            'color' => 'Yellow',
            'seats' => 2,
            'grade_overall' => 4.9,
            'grade_exterior' => 'A',
            'grade_interior' => 'A',
            'price_amount' => 350000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'ZHW******K******',
            'location' => 'Tokyo, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Exotic supercar in perfect condition',
        ]);

        Car::create([
            'category_id' => $suvs->id,
            'ref_no' => 'CAR-SUV-003',
            'make' => 'Mitsubishi',
            'model' => 'Pajero',
            'model_code' => 'MPAJ',
            'variant' => 'GLS',
            'year' => 2018,
            'reg_year_month' => '2018-12',
            'mileage_km' => 65000,
            'engine_cc' => 3200,
            'transmission' => 'Automatic',
            'drive' => '4WD',
            'steering' => 'Right',
            'fuel' => 'Diesel',
            'color' => 'Green',
            'seats' => 7,
            'grade_overall' => 3.8,
            'grade_exterior' => 'C',
            'grade_interior' => 'B',
            'price_amount' => 45000.00,
            'price_currency' => 'USD',
            'price_basis' => 'FOB',
            'chassis_no_masked' => 'JMY******K******',
            'location' => 'Sapporo, Japan',
            'country_origin' => 'Japan',
            'status' => 'available',
            'notes' => 'Off-road capable SUV',
        ]);
    }
}
